name: OpenMod.Rust.Oxide.PermissionLink

on:
  create:
    tags:
      - "*"
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/OpenMod.Rust.Oxide.PermissionLink.yaml'
      - 'rust/oxide/OpenMod.Rust.Oxide.PermissionLink/**'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/OpenMod.Rust.Oxide.PermissionLink.yaml'
      - 'rust/oxide/OpenMod.Rust.Oxide.PermissionLink/**'

jobs:
  build:
    name: "OpenMod.Rust.Oxide.PermissionLink Build"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-dotnet@v3
      name: Setup .NET
      with:
        dotnet-version: 7.x
    - uses: ././.github/actions/project-build
      id: project-build
      with:
        project_path: rust/oxide/OpenMod.Rust.Oxide.PermissionLink
        github_token: ${{ secrets.GITHUB_TOKEN }}
        nuget_key: ${{ secrets.NUGET_DEPLOY_KEY }}
        nuget_push: true
