name: OpenMod.NuGet

on:
  create:
    tags:
      - "*"
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/OpenMod.NuGet.yaml'
      - 'framework/OpenMod.NuGet/**'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/OpenMod.NuGet.yaml'
      - 'framework/OpenMod.NuGet/**'

jobs:
  build:
    name: "OpenMod.NuGet Build"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-dotnet@v3
      name: Setup .NET
      with:
        dotnet-version: 7.x
    - uses: ./.github/actions/project-build
      id: project-build
      with:
        project_path: framework/OpenMod.NuGet
        github_token: ${{ secrets.GITHUB_TOKEN }}
        nuget_key: ${{ secrets.NUGET_DEPLOY_KEY }}
        nuget_push: true
