name: OpenMod.Standalone

on:
  release:
    types: [ published ]
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/OpenMod.Standalone.yaml'
      - 'standalone/**'
      - 'framework/**'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/OpenMod.Standalone.yaml'
      - 'standalone/**'
      - 'framework/**'

jobs:
  build:
    name: "OpenMod.Standalone Build"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: Checkout Repository
      with:
        fetch-depth: 0
    - uses: actions/setup-dotnet@v3
      name: Setup .NET
      with:
        dotnet-version: 7.x
    - uses: ./.github/actions/project-build
      id: project-build
      with:
        project_path: standalone/OpenMod.Standalone
        nuget_push: false
    - name: Get Release
      if: github.event_name == 'release'
      id: get-release
      uses: bruceadams/get-release@v1.2.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Install zip
      if: github.event_name == 'release'
      run: sudo apt-get install zip
    - name: Zip net461 artifacts
      if: github.event_name == 'release'
      run: "cd ./standalone/OpenMod.Standalone/bin/Release/net461 && zip -qq -r ./release.zip *"
    - name: Upload net461 release asset
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get-release.outputs.upload_url }}
        asset_path: ./standalone/OpenMod.Standalone/bin/Release/net461/release.zip
        asset_name: OpenMod.Standalone-v${{ steps.project-build.outputs.version }}-net461.zip
        asset_content_type: application/zip
    - name: Zip netcoreapp3.1 artifacts
      if: github.event_name == 'release'
      run: "cd ./standalone/OpenMod.Standalone/bin/Release/netcoreapp3.1 && zip -qq -r ./release.zip *"
    - name: Upload netcoreapp3.1 release asset
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get-release.outputs.upload_url }}
        asset_path: ./standalone/OpenMod.Standalone/bin/Release/netcoreapp3.1/release.zip
        asset_name: OpenMod.Standalone-v${{ steps.project-build.outputs.version }}-netcoreapp3.1.zip
        asset_content_type: application/zip
