name: OpenMod.Rust.Oxide.Extension

on:
  create:
    tags:
      - "*"
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/OpenMod.Rust.Oxide.Extension.yaml'
      - 'rust/oxide/OpenMod.Rust.Oxide.Extension/**'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/OpenMod.Rust.Oxide.Extension.yaml'
      - 'rust/oxide/OpenMod.Rust.Oxide.Extension/**'

jobs:
  build:
    name: "OpenMod.Rust.Oxide.Extension Build"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-dotnet@v3
      name: Setup .NET
      with:
        dotnet-version: 7.x
    - uses: ././.github/actions/project-build
      id: project-build
      with:
        project_path: rust/oxide/OpenMod.Rust.Oxide.Extension
        nuget_push: false
