name: OpenMod.EntityFrameworkCore.MySql

on:
  create:
    tags:
      - "*"
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/OpenMod.EntityFrameworkCore.MySql.yaml'
      - 'framework/OpenMod.EntityFrameworkCore.MySql/**'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/OpenMod.EntityFrameworkCore.MySql.yaml'
      - 'framework/OpenMod.EntityFrameworkCore.MySql/**'

jobs:
  build:
    name: "OpenMod.EntityFrameworkCore.MySql Build"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-dotnet@v3
      name: Setup .NET
      with:
        dotnet-version: 7.x
    - uses: ./.github/actions/project-build
      id: project-build
      with:
        project_path: framework/OpenMod.EntityFrameworkCore.MySql
        github_token: ${{ secrets.GITHUB_TOKEN }}
        nuget_key: ${{ secrets.NUGET_DEPLOY_KEY }}
        nuget_push: true
